# Back to the Basics
Learn Neural Networks by implementing the most basic operations

In [116]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## OR
### Generate Training Data

In [320]:
x1 = (torch.ones(16, 16) * torch.arange(16)).type(torch.int8)
x2 = x1.clone().T
x = torch.stack((x1, x2)).transpose(0, 2).flatten(0, 1)
x.shape 

TypeError: ones() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [211]:
y = torch.bitwise_or(x[:, 0], x[:, 1]).unsqueeze(-1)
y.shape

torch.Size([256, 1])

#### For viewing pleasure

In [226]:
torch.cat((x.T, y.T)).view(3, 16, 16).transpose(0, 1)

tensor([[[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]],

        [[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
         [ 1,  1,  3,  3,  5,  5,  7,  7,  9,  9, 11, 11, 13, 13, 15, 15]],

        [[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
         [ 2,  3,  2,  3,  6,  7,  6,  7, 10, 11, 10, 11, 14, 15, 14, 15]],

        [[ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
         [ 3,  3,  3,  3,  7,  7,  7,  7, 11, 11, 11, 11, 15, 15, 15, 15]],

        [[ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
         [ 0,  1,

### Prepare Training Data

In [276]:
Xtr = x.float()
Ytr = y.float()

print("Xtr: ", Xtr.shape, Xtr.dtype)
print("Ytr: ", Ytr.shape, Ytr.dtype)


Xtr:  torch.Size([256, 2]) torch.float32
Ytr:  torch.Size([256, 1]) torch.float32


#### Initialize Neural Net

In [303]:
model = nn.Linear(8, 4)
optim = torch.optim.SGD(model.parameters())
lossf = nn.CrossEntropyLoss()

### Train

In [308]:
logits = model(Xtr)
loss = lossf(logits, Ytr)
print("loss:", loss)
optim.zero_grad()
loss.backward()
optim.step()

loss: tensor(-0., grad_fn=<DivBackward1>)


In [307]:
logits

tensor([[ 0.3945],
        [ 0.5749],
        [ 0.7553],
        [ 0.9357],
        [ 1.1161],
        [ 1.2965],
        [ 1.4769],
        [ 1.6573],
        [ 1.8377],
        [ 2.0181],
        [ 2.1985],
        [ 2.3789],
        [ 2.5593],
        [ 2.7397],
        [ 2.9201],
        [ 3.1005],
        [ 0.1469],
        [ 0.3273],
        [ 0.5077],
        [ 0.6881],
        [ 0.8685],
        [ 1.0489],
        [ 1.2293],
        [ 1.4097],
        [ 1.5901],
        [ 1.7705],
        [ 1.9509],
        [ 2.1313],
        [ 2.3117],
        [ 2.4921],
        [ 2.6725],
        [ 2.8529],
        [-0.1007],
        [ 0.0797],
        [ 0.2601],
        [ 0.4405],
        [ 0.6209],
        [ 0.8013],
        [ 0.9817],
        [ 1.1621],
        [ 1.3425],
        [ 1.5229],
        [ 1.7033],
        [ 1.8837],
        [ 2.0641],
        [ 2.2445],
        [ 2.4249],
        [ 2.6053],
        [-0.3483],
        [-0.1679],
        [ 0.0125],
        [ 0.1929],
        [ 0.

In [305]:
for p in model.parameters():
    print(p.data, p.grad)

tensor([[-0.2476,  0.1804]]) tensor([[0., 0.]])
tensor([0.3945]) tensor([0.])


<generator object Module.parameters at 0x7a1f52de5310>

In [113]:
list(params)

[Parameter containing:
 tensor([[-0.6536,  0.2446]], requires_grad=True),
 Parameter containing:
 tensor([0.1718], requires_grad=True)]